POST http://localhost:8080/issue
Content-Type: application/json

{
  "title": "테스트 이슈",
  "description": "테스트 중입니다.",
  "userId": 1
}

###

GET http://localhost:8080/issues

###

GET http://localhost:8080/issue/1

PATCH http://localhost:8080/issue/1
Content-Type: application/json

{
  "title": "로그인 버그 수정",
  "status": "IN_PROGRESS",
  "userId": 2
}


### 필수값 누락
POST http://localhost:8080/issue
Content-Type: application/json

{
  "description": "타이틀 없음"
}

### 존재하지 않는 사용자
POST http://localhost:8080/issue
Content-Type: application/json

{
  "title": "테스트",
  "userId": 999
}

### 잘못된 ID로 수정
PATCH http://localhost:8080/issue/abc
Content-Type: application/json

{
  "title": "에러"
}

### 존재하지 않는 이슈 수정
PATCH http://localhost:8080/issue/999
Content-Type: application/json

{
  "title": "에러"
}

### 존재하지 않는 상태로 수정
PATCH http://localhost:8080/issue/1
Content-Type: application/json

{
  "status": "DOING"
}

### 담당자 없는 상태에서 IN_PROGRESS 설정
PATCH http://localhost:8080/issue/1
Content-Type: application/json

{
  "userId": null,
  "status": "IN_PROGRESS"
}

### 존재하지 않는 유저로 할당 시도
PATCH http://localhost:8080/issue/1
Content-Type: application/json

{
  "userId": 999
}

PATCH http://localhost:8080/issue/1
Content-Type: application/json

{
  "status": "DOING"
}
